[window]
opacity = 0.8
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true

[window.dimensions]
columns = 67
lines = 25

[window.padding]
x = 25
y = 25

[scrolling]
history = 10000
multiplier = 1

#[terminal]
#tabspaces = 8

[font]
size = 11.0

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 750
unfocused_hollow = true

[mouse]
hide_when_typing = true

#[keyboard]
#alt_send_esc = true

[hints]
[[hints.enabled]]
regex = "(https?://[^\\s]+)"
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "None"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
